### PR TITLE
Check branch review 

### PR DESCRIPTION
**Pull request by ARAVIND472A**
Check this file and update me

### CODE REVIEW

**Review by Domnicdev — COMMENTED** [review]
Hi Aravind, I reviewed your file
1.Your controller class file name is not appropriate, kindly change it .
2.And your delete method name is not by coding standard so kindly look on to that.

**Comment by ARAVIND472A** [comment]
> Hi Aravind, I reviewed your file 1.Your controller class file name is not appropriate, kindly change it . 2.And your delete method name is not by coding standard so kindly look on to that.

Thank you domnic ,I resolved it now

**Comment by Domnicdev** [comment]
And Also there is an unwanted import statement ("import java.util.LinkedList") in customerdao.java file, please remove that also

**Comment by ARAVIND472A** [comment]
> And Also there is an unwanted import statement ("import java.util.LinkedList") in customerdao.java file, please remove that also

Thank you domnic ,I resolved it now.Have a look

**Comment by Domnicdev** [comment]
Every other things are fine, Thank you

**Review by Purushothaman1962 — COMMENTED** [review]
1. In Customer.java remove the unused import statement Array list and Linked list.
2. In CMSController.java remove the unused import statement Linked list and modify the method name PerformInsert and PerformUpdate to performInsert and performUpdate.

**Comment by ARAVIND472A** [comment]
> 1. In Customer.java remove the unused import statement Array list and Linked list.
> 2. In CMSController.java remove the unused import statement Linked list and modify the method name PerformInsert and PerformUpdate to performInsert and performUpdate.

Thank you Purushothaman, I resolved the bug,Have a look

**Comment by Purushothaman1962** [comment]
Ok Aravind fine you can merge it. Thank You

**Pull request merged**
